server:
  error:
    include-message: always
    include-binding-errors: always
app:
  auth:
    tokenSecret: bulbazaurus666!@#$%^&*()
    tokenExpirationMsec: 600000

spring:
  data:
    mongodb:
      port: 27017
      host: localhost
      database: test