server:
  error:
    include-message: always
    include-binding-errors: always
app:
  auth:
    tokenSecret: bulbazaurus666!@#$%^&*()
    tokenExpirationMsec: 600000

spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 12MB